spring.application.name=shareit
spring.main.banner-mode=off
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=dbuser
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.sql.init.mode=always